[program:bagm_cancer_relative_data_prep]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/bagm-cancer-relative-data-prep.sh
directory=/workspace/BAGM
autostart=false
autorestart=false
startsecs=0
stopsignal=TERM
stopwaitsecs=120
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
